server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/enrollments/**
        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/exams/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /auth/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
